title: idvogados
description: Uma comunidade volunt√°ria
# logo: [Location of the logo]
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]
# plugins:
  # - jekyll-relative-links
# relative_links:
  # enabled: true
  # collections: true
include:
  - README.md
theme: jekyll-theme-minimal